### ISSUE TITLE
Can't parse the website

### ISSUE THREAD

**Issue by AmmerB** [reconhub/course-malta-2018#4]
My Rstudio won't parse the website: 
`error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"\..\...\Hugo\hugo.exe" -b / -D -F -d "public" -t hugo-icon' execution failed with error code 1`

Did add all the facilitators for the course except Jonny, pictures also in the right folders. Not urgent but if you have time could you have a look?

**Comment by zkamvar** [comment]
It should be fixed now. There was a missing "twitter" tag for Pat's profile.
